# .streamlit/config.toml

[server]
headless = true
enableCORS = false
port = 8501

[theme]
primaryColor = "#1E88E5"
backgroundColor = "#E3F2FD"
secondaryBackgroundColor = "#FFFFFF"
font = "sans serif"
